// Computer_System_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.1 590

`timescale 1 ps / 1 ps
module Computer_System_mm_interconnect_1 (
		input  wire        SYSTEM_PLL_sys_clk_clk,                      //                    SYSTEM_PLL_sys_clk.clk
		input  wire        DMA_WRITE_reset_reset_bridge_in_reset_reset, // DMA_WRITE_reset_reset_bridge_in_reset.reset
		input  wire [31:0] DMA_WRITE_avalon_dma_master_address,         //           DMA_WRITE_avalon_dma_master.address
		output wire        DMA_WRITE_avalon_dma_master_waitrequest,     //                                      .waitrequest
		input  wire        DMA_WRITE_avalon_dma_master_write,           //                                      .write
		input  wire [7:0]  DMA_WRITE_avalon_dma_master_writedata,       //                                      .writedata
		output wire [18:0] RAM_s1_address,                              //                                RAM_s1.address
		output wire        RAM_s1_write,                                //                                      .write
		input  wire [7:0]  RAM_s1_readdata,                             //                                      .readdata
		output wire [7:0]  RAM_s1_writedata,                            //                                      .writedata
		output wire        RAM_s1_chipselect,                           //                                      .chipselect
		output wire        RAM_s1_clken                                 //                                      .clken
	);

	wire         dma_write_avalon_dma_master_translator_avalon_universal_master_0_waitrequest;   // RAM_s1_translator:uav_waitrequest -> DMA_WRITE_avalon_dma_master_translator:uav_waitrequest
	wire   [7:0] dma_write_avalon_dma_master_translator_avalon_universal_master_0_readdata;      // RAM_s1_translator:uav_readdata -> DMA_WRITE_avalon_dma_master_translator:uav_readdata
	wire         dma_write_avalon_dma_master_translator_avalon_universal_master_0_debugaccess;   // DMA_WRITE_avalon_dma_master_translator:uav_debugaccess -> RAM_s1_translator:uav_debugaccess
	wire  [31:0] dma_write_avalon_dma_master_translator_avalon_universal_master_0_address;       // DMA_WRITE_avalon_dma_master_translator:uav_address -> RAM_s1_translator:uav_address
	wire         dma_write_avalon_dma_master_translator_avalon_universal_master_0_read;          // DMA_WRITE_avalon_dma_master_translator:uav_read -> RAM_s1_translator:uav_read
	wire   [0:0] dma_write_avalon_dma_master_translator_avalon_universal_master_0_byteenable;    // DMA_WRITE_avalon_dma_master_translator:uav_byteenable -> RAM_s1_translator:uav_byteenable
	wire         dma_write_avalon_dma_master_translator_avalon_universal_master_0_readdatavalid; // RAM_s1_translator:uav_readdatavalid -> DMA_WRITE_avalon_dma_master_translator:uav_readdatavalid
	wire         dma_write_avalon_dma_master_translator_avalon_universal_master_0_lock;          // DMA_WRITE_avalon_dma_master_translator:uav_lock -> RAM_s1_translator:uav_lock
	wire         dma_write_avalon_dma_master_translator_avalon_universal_master_0_write;         // DMA_WRITE_avalon_dma_master_translator:uav_write -> RAM_s1_translator:uav_write
	wire   [7:0] dma_write_avalon_dma_master_translator_avalon_universal_master_0_writedata;     // DMA_WRITE_avalon_dma_master_translator:uav_writedata -> RAM_s1_translator:uav_writedata
	wire   [0:0] dma_write_avalon_dma_master_translator_avalon_universal_master_0_burstcount;    // DMA_WRITE_avalon_dma_master_translator:uav_burstcount -> RAM_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (8),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (1),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (1),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (1),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) dma_write_avalon_dma_master_translator (
		.clk                    (SYSTEM_PLL_sys_clk_clk),                                                         //                       clk.clk
		.reset                  (DMA_WRITE_reset_reset_bridge_in_reset_reset),                                    //                     reset.reset
		.uav_address            (dma_write_avalon_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (dma_write_avalon_dma_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (dma_write_avalon_dma_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (dma_write_avalon_dma_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (dma_write_avalon_dma_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (dma_write_avalon_dma_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (dma_write_avalon_dma_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (dma_write_avalon_dma_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (dma_write_avalon_dma_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (dma_write_avalon_dma_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (dma_write_avalon_dma_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (DMA_WRITE_avalon_dma_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (DMA_WRITE_avalon_dma_master_waitrequest),                                        //                          .waitrequest
		.av_write               (DMA_WRITE_avalon_dma_master_write),                                              //                          .write
		.av_writedata           (DMA_WRITE_avalon_dma_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                           //               (terminated)
		.av_byteenable          (1'b1),                                                                           //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                           //               (terminated)
		.av_begintransfer       (1'b0),                                                                           //               (terminated)
		.av_chipselect          (1'b0),                                                                           //               (terminated)
		.av_read                (1'b0),                                                                           //               (terminated)
		.av_readdata            (),                                                                               //               (terminated)
		.av_readdatavalid       (),                                                                               //               (terminated)
		.av_lock                (1'b0),                                                                           //               (terminated)
		.av_debugaccess         (1'b0),                                                                           //               (terminated)
		.uav_clken              (),                                                                               //               (terminated)
		.av_clken               (1'b1),                                                                           //               (terminated)
		.uav_response           (2'b00),                                                                          //               (terminated)
		.av_response            (),                                                                               //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                           //               (terminated)
		.av_writeresponsevalid  ()                                                                                //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (19),
		.AV_DATA_W                      (8),
		.UAV_DATA_W                     (8),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (1),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (1),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (1),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) ram_s1_translator (
		.clk                    (SYSTEM_PLL_sys_clk_clk),                                                         //                      clk.clk
		.reset                  (DMA_WRITE_reset_reset_bridge_in_reset_reset),                                    //                    reset.reset
		.uav_address            (dma_write_avalon_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (dma_write_avalon_dma_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (dma_write_avalon_dma_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (dma_write_avalon_dma_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (dma_write_avalon_dma_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (dma_write_avalon_dma_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (dma_write_avalon_dma_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (dma_write_avalon_dma_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (dma_write_avalon_dma_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (dma_write_avalon_dma_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (dma_write_avalon_dma_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (RAM_s1_address),                                                                 //      avalon_anti_slave_0.address
		.av_write               (RAM_s1_write),                                                                   //                         .write
		.av_readdata            (RAM_s1_readdata),                                                                //                         .readdata
		.av_writedata           (RAM_s1_writedata),                                                               //                         .writedata
		.av_chipselect          (RAM_s1_chipselect),                                                              //                         .chipselect
		.av_clken               (RAM_s1_clken),                                                                   //                         .clken
		.av_read                (),                                                                               //              (terminated)
		.av_begintransfer       (),                                                                               //              (terminated)
		.av_beginbursttransfer  (),                                                                               //              (terminated)
		.av_burstcount          (),                                                                               //              (terminated)
		.av_byteenable          (),                                                                               //              (terminated)
		.av_readdatavalid       (1'b0),                                                                           //              (terminated)
		.av_waitrequest         (1'b0),                                                                           //              (terminated)
		.av_writebyteenable     (),                                                                               //              (terminated)
		.av_lock                (),                                                                               //              (terminated)
		.uav_clken              (1'b0),                                                                           //              (terminated)
		.av_debugaccess         (),                                                                               //              (terminated)
		.av_outputenable        (),                                                                               //              (terminated)
		.uav_response           (),                                                                               //              (terminated)
		.av_response            (2'b00),                                                                          //              (terminated)
		.uav_writeresponsevalid (),                                                                               //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                            //              (terminated)
	);

endmodule
